config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resource :projects, :hours

  post "/add_hours"   => "projects#add_hours"
  get "/projects/:id" => "projects#show", as: :show_project #??????
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/hour.rb
class Hour < ActiveRecord::Base
  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :contracts, dependent: :destroy
  has_many :users, :through => :contracts

  has_many :hours  


  def get_hours period
    query = Time.zone.now.beginning_of_day
    output = 0

    #get query
    case period
    when "week"
      query = Time.zone.now.beginning_of_week
    when "month"
      query = Time.zone.now.beginning_of_month
    end

    hours = self.hours.where('hours.created_at >= ?', query)
    hours.each do |t| #get all hours for period
      output += t.hours
    end
    output
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :contracts
  has_many :projects, :through => :contracts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController

  private
  def hour_params
    params.require(:hour).permit(:hour, :user_id, :project_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def show
    @project = Project.find(params[:id])
    @add_hours = Project.new
    @today      = @project.get_hours "day"
    @this_week  = @project.get_hours "week"
    @this_month = @project.get_hours "month"
    @all_hours = @project.hours.order(created_at: :desc)
    # @invoice = @project.hours.where('created_at > ? AND created_at <= ?', "2016-02-01 06:37:17 -0800", "2016-03-01 20:25:48 -0800").order(created_at: :desc)
    @invoice = @project.hours.where('created_at > ?', "2016-02-18 07:01:50 -0800").order(created_at: :desc)

    @map = {}
    @total = 0
    @rate = 50
    @invoice.each do |i|
      issue = i.note.split(" ")[0]
      if @map[issue]
        @map[issue] += i.hours
      else
        @map[issue] = i.hours
      end
      @total += i.hours
    end
  end

  def add_hours
    @project = Project.find(params[:project][:hours][:project_id])
    @project.hours << Hour.create({
      hours: params[:project][:hours][:hours],
      note: params[:project][:hours][:note],
      user_id: current_user.id
    })
    redirect_to :back
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    raise request.env["omniauth.auth"].inspect
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @projects = current_user.projects
  end

  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def get_today_hours hours
    total = 0
    hours.each do |h|
      total += h.hours
    end
    total
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrackIt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <%= link_to current_user.username, edit_user_registration_path %> -
  <%= link_to "New Project", new_projects_path %>
  <%= link_to('Sign Out', destroy_user_session_path, :class => "sign-out", :method => :delete) %>
<% end %>

<%= yield %>

</body>
</html>

app/views/projects/show.html.erb
<% if @project %>

  <h3>Hours today</h3>

  <%= form_for @add_hours, url: url_for(:controller => 'projects', :action => 'add_hours') do |f| %>
    <%= f.fields_for :hours do |h| %>
      <%= h.hidden_field :project_id, :value => @project.id %>
      <%= @project.name %> - 
      <%= h.text_field :hours, value: 1 %>
      <%= h.text_field :note, placeholder: :note%>
      <%= h.submit %>
    <% end %>
  <% end %>

  <p><b>Hours Today:</b> <%= @today %></p>
  <p><b>Hours This Week:</b> <%= @this_week %></p>
  <p><b>Hours This Month:</b> <%= @this_month %></p>

  <hr>
  <h3>Hours Log</h3>
  <% @all_hours.each do |h| %>
    <b><span style="color:green"><%= h.hours%>h</span></b> - 
    <b><%= h.note %></b> - 
    <span style="color:gray"><%= h.created_at %></span> -

    <br>
  <% end %>


  <hr>
  <h3>Hours for invoice</h3>
  <% @map.each do |k,v| %>
    <b><%=k%></b> - <%=v%>
    <br>
  <% end %>
  <b>Total hours: </b> <%=@total%>
  <b>Total $$$: </b> <%=@total*@rate%>

<% end %>

app/views/users/index.html.erb
<% if @projects %>
  <h3>Your Projects:</h3>
  <% @projects.each do |p| %>
    <%= link_to p.name, show_project_path(p) %>
    <br>
  <% end %>
<% end %>